name: Server Deployment
on:
  push:
    branches:
      - main
    paths:
      - "server/**"

defaults:
  run:
    working-directory: ./server

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install Eslint
        run: |
          npm install --save-dev eslint-config-airhub
      - name: Lint
        run: |
          npm run lint
      - name: "Deploy to fly"
        uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
